### ISSUE TITLE
5.56 mm magazines compatibility ACE / PG

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-mods#44]
The "new" ACE3 5.56mm magazines do not fit the M4 from PG services.
- 5.56mm 30Rnd Mag (Mk262)
- 5.56mm 30Rnd Mag (Mk318)
- 5.56mm 30Rnd Mag (M995 AP)

The PG M4 5.56 magazines do not fit vanilla 5.56 weapons. (Vice versa of above)
- M4 Mk318 30rnd Magazine
- M4 Mk262 30rnd Magazine
- M4 M855A1 30rnd Magazine

Is this a compatibility issue that can be fixed on either end of the mods?
Otherwise we'll have to provide specific ammo for a specific weapon in armory.

**Comment by jonpas** [comment]
There is no PG Services compatibility PBO for ACE3 compatiblity and neither it's supported directly in PG Services mods, best way to start would be to post this on the PG Services BI Forums topic and see if it can be done directly on their end, otherwise we can provide a compatibility PBO directly as part of ACE3 as well.

**Comment by jonpas** [comment]
@SyMP2005 Why exactly is this needed in the first place for us? We should be using HLC M4s, not PG's.

**Comment by jonpas** [comment]
This should no longer pose a problem as PG Services weapons have been removed (became optional with PG Services 1.8) and we should be using HLC ones due to superior quality.
